### ISSUE TITLE
Project difficulty is missing

### ISSUE THREAD

**Issue by findmyway** [JuliaCN/ProjectIdeas#4]
Hi @GiggleLiu , @ChenZhao44 , and @johnnychen94 ,

The deadline to submit OSPP proposals is approaching. I'm about to submit all the proposals here. But the `difficulty` of each project is still missing. Each project should be classified as either **Basic** or **Advanced** (for example: [diff_en.pdf](https://github.com/JuliaCN/ProjectIdeas/files/11257356/diff_en.pdf)). Please help update it ASAP.

**Comment by ChenZhao44** [comment]
Thank you @findmyway ! Both two of my projects have the difficulty **Advanced**. Could you help me to update it?

**Comment by johnnychen94** [comment]
julia-packing: #5
