### ISSUE TITLE
Each mentor can only guide one project

### ISSUE THREAD

**Issue by findmyway** [JuliaCN/ProjectIdeas#6]
Hi @GiggleLiu  and @ChenZhao44 ,

According to the official doc: https://summer-ospp.ac.cn/help/en/mentor/#2-how-to-become-a-mentor , each mentor can only guide ONE project. And it seems I can only submit one project proposal per mentor on the portal. So please let me know which one you would like to guide. Or, could you find someone else to help mentor the extra two projects?

**Comment by GiggleLiu** [comment]
The TropicalGEMM one please.

**Comment by ChenZhao44** [comment]
The [ZXW-calculus](https://github.com/JuliaCN/ProjectIdeas/tree/main/zx-calculus) one please. Thanks!

**Comment by findmyway** [comment]
Submitted!

Ping me if you find some other mentors to guide the rest projects.
